comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

#added from codecov
codecov:
token: f83d302b-4584-4f68-af20-0a6eca512469
